source_roots = ["src"]
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
forbid_circular_dependencies = true

# Architecture layers can only import from below
layers = [
    "entrypoints",
    "config",
    "business_logic",
]

# Data can only be fetched through the interface
[[interfaces]]
expose = ["fetch_data", "load_sql_files", "process_data"]
from = ["project.data"]

# Modules in the layers
[[modules]]
path = "project.entrypoints/**"
layer = "entrypoints"
depends_on = []

[[modules]]
path = "project.config"
layer = "config"
depends_on = []

[[modules]]
path = "project.models"
layer = "business_logic"
depends_on = []

[[modules]]
path = "project.features"
layer = "business_logic"
depends_on = []

[[modules]]
path = "project.data"
layer = "business_logic"
depends_on = []

# Utilities can be imported freely
[[modules]]
path = "project.types"
utility = true
depends_on = []

[[modules]]
path = "project.util"
utility = true
depends_on = []

[[modules]]
path = "project.version"
utility = true
depends_on = []
