register_model: null
experiment:
  name: null
  description: ???

run_name: ${hydra:sweep.subdir}
hydra:
  mode: MULTIRUN
  sweep:
    subdir: ${hydra.job.num}-${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - experiment
  callbacks:
    parent_run:
      _target_: project.config.ParentRunCallback
      name: ${oc.select:experiment.name,${hydra.job.name}-${hydra.job.config_name}_${now:%Y%m%d}_${now:%H%M%S}}
      description: ${experiment.description}
  sweeper:
    params: ???
